name: Build

on:
  push:
    branches:
      - master  # Trigger on push to master branch

jobs:
  build:
    name: Build and analyze
    runs-on: [self-hosted, linux]  # Specify self-hosted runner with a Linux environment
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is fetched for accurate analysis
    
      - name: Set up JDK 17 (if applicable)
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Set up Java environment, change if using a different language

      - name: Run SonarQube scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Token for SonarQube authentication
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # URL of your SonarQube server
    
      # Uncomment this if you want to fail the job when the Quality Gate is red (failing analysis)
      # - name: Check SonarQube Quality Gate
      #   uses: sonarsource/sonarqube-quality-gate-action@v2
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}