name: Build and Analyze

on:
  push:
    branches:
      - master  # Adjust if you want other branches to trigger this workflow

jobs:
  build:
    runs-on: ubuntu-latest  # Use a GitHub-hosted runner, such as Ubuntu, Windows, or macOS
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # This checks out your code repository to the runner

      - name: Set up SonarQube scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # SonarQube authentication token
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # SonarQube server URL

      - name: Run SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # SonarQube authentication token
